### ISSUE TITLE
Migrate from Matt's teslamate add-on to lildude's

### ISSUE THREAD

**Issue by shivaagarwal1** [lildude/ha-addon-teslamate#3]
Hi Lildue,

Many thanks for taking over this add-on. I have added your repo but don't see Teslamate as an add-on. Further, how do I migrate to your version of add-on without losing my data from the previous one?

Thanks,
Shiva

**Comment by shivaagarwal1** [comment]
> TeslaMate will only become availave in my add-ons repo when I've merged [lildude/ha-addons#17](https://github.com/lildude/ha-addons/pull/17).
> 
> I've deliberately not done this year as I'm still ironing out a few things in this repo, including writing steps for migrating without losing data; there shouldn't be any as we're leaving the DB etc as-is, but I still need to test this to be 100% sure and write it down for others.

Thank you updating the add-on and writing the migration steps. Now just eagerly waiting for the add-on to be included in your add-on repository. Thank you for all your hard work.

**Comment by gerione** [comment]
Migration worked beautifully :) Thanks for your effort.
