### ISSUE TITLE
scan_interval configure?

### ISSUE THREAD

**Issue by eried** [lildude/ha-addon-teslamate#34]
Hi, thanks for the addon! Works perfectly. How can I make the scan interval less frequent? I see the "third api app access" icon blinking very frequently in my car

**Comment by lildude** [comment]
This is really a question for the upstream project, but I believe you can adjust the various polling intervals by setting the appropriate environment variables as detailed [here](https://docs.teslamate.org/docs/configuration/environment_variables).

You can do this in the addon by adding them and their values to the [`env_vars` configuration option](https://github.com/lildude/ha-addon-teslamate/blob/main/DOCS.md) and restart the addon.

None of these are named `scan_interval` though. The only `scan_interval` I know of is the one detailed [here](https://docs.teslamate.org/docs/integrations/home_assistant) which you can add to your `configuration.yaml` file.

**Comment by eried** [comment]
Thanks @lildude

**Comment by eried** [comment]
For reference (for a future github traveller) I am trying with the following `env_vars` in the config. But I might be confused on how the polling works, so it is just testing for now

```

- POLLING_ASLEEP_INTERVAL: 300
- POLLING_CHARGING_INTERVAL: 30
- POLLING_DRIVING_INTERVAL: 300
- POLLING_ONLINE_INTERVAL: 60
- POLLING_DEFAULT_INTERVAL: 60
- POLLING_MINIMUM_INTERVAL: 30
```
