### ISSUE TITLE
Grafana showing error: Failed to upgrade legacy queries.

### ISSUE THREAD

**Issue by WLammert** [lildude/ha-addon-teslamate#39]
After successfull installing the Postgres, Grafana and this TeslaMate addons I see that dashboards are created in grafana, and the correct car data is show in the TeslaMate UI
<img width="809" alt="image" src="https://github.com/user-attachments/assets/85cf3ab2-9e00-4a57-b5e5-7411e4a30417">

Sadly something seems not to be working as I get this view when it comes to grafana:
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/d8d88da0-0272-4879-84ce-eaa913636206">

Does someone has any idea what could be wrong?

**Comment by lildude** [comment]
I recommend posting this on the upstream TeslaMate [issues](https://github.com/teslamate-org/teslamate/issues) or [discussions](https://github.com/teslamate-org/teslamate/discussions) as this addon is just repackaging their work.

**Comment by WLammert** [comment]
Ah, allright. I’ll try my luck there.
