### ISSUE TITLE
Problem access port 4000 addon HomeAssitant

### ISSUE THREAD

**Issue by cortesmario** [lildude/ha-addon-teslamate#41]
Hi,

I have the sytem working on my HomeAssistant Green:

- Teslamate --> OK
- Grafana --> OK
- Postgres --> OK

But the only problem, that I have is I access Teslamate app from the web interface, but if I try to access outside from HomeAssistant, doesn´t work I try the http://%IP%:4000 at web and doesn´t work.

I try with curl, and I can´t access to port 4000

What can I check to try to find the error? 

Thanks and best regards,
Mario

**Comment by lildude** [comment]
Direct port access was removed in https://github.com/matt-FFFFFF/hassio-addon-teslamate/pull/1 when ingress support was added. The empty port options were then removed in https://github.com/matt-FFFFFF/hassio-addon-teslamate/pull/69. These both happened looog before I took over maintaining this extension.

**Comment by cortesmario** [comment]
Ok,
I change one option at Teslamate, to add geofences, that I can do.
I close the issue.

Thanks,
Mario
