### ISSUE TITLE
Documentation needs upgrading

### ISSUE THREAD

**Issue by thestumonkey** [lildude/ha-addon-teslamate#50]
Trying to get this addon working, but the documentation is pretty barebones.
I get teslamate up and running, but there's a settings page with URL's for "app" and "dashboards".
It's unclear what should be entered in here, but I can only get it to link out to the grafana main page rather than pulling in the grafana board into the teslamate app.
What am I missing here?

**Comment by lildude** [comment]
Those aren't settings within the addon, they're settings within the upstream app this addon bundles up.

You should open an issue with the upstream project.

**Comment by lildude** [comment]
Whoops. I forgot to tell you what to put in those boxes 🤦 

Set the Web App URL to the path of the ingress iframe that is shown when you click "Open Web UI" in the addon. This will be something like: `https://ha.example.com/api/hassio_ingress/[a long string of chars]/settings`.


I've got the Dashboards URL set to `https://ha.example.com/a0d7b954_grafana/dashboard` but I note it doesn't seem to load the correct graph when selected from the TeslaMate UI anymore. I'm not sure why. Maybe the upstream maintainer can provide more insight.
